version: '3.7'
services:
  mongo:
    image: mongo:4.1.13-bionic
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    environment:
      NODE_ENV: production
    depends_on:
      - mongo
    ports:
      - 4000:4000
